param(
  [string]$ProjectRoot = "D:\simras-digital-twin-repository\simras-digital-twin"
)

$ErrorActionPreference = "Stop"
Set-Location $ProjectRoot
[Environment]::CurrentDirectory = (Get-Location).Path

$stamp = Get-Date -Format "yyyyMMdd_HHmmss"
$backup = Join-Path $ProjectRoot "archive\twin_source_reset_$stamp"
New-Item -ItemType Directory -Force $backup | Out-Null

$files = @(
  ".\frontend\src\features\digital-twin\TwinPanels.tsx",
  ".\frontend\src\features\digital-twin\EvidenceStatePanel.tsx"
)

foreach ($file in $files) {
  if (Test-Path $file) {
    Copy-Item $file (Join-Path $backup (Split-Path $file -Leaf)) -Force
  }
}

Write-Host "`n=== 1. RESTORE KNOWN-GOOD TWIN PANELS ===" -ForegroundColor Cyan

[IO.File]::WriteAllBytes(
  ".\frontend\src\features\digital-twin\TwinPanels.tsx",
  [Convert]::FromBase64String("aW1wb3J0IHR5cGUgeyBUd2luUmVzcG9uc2UgfSBmcm9tICIuLi8uLi90eXBlcy90d2luIjsKaW1wb3J0IHsgcmlza0NvbG9yIH0gZnJvbSAiLi4vLi4vdXRpbHMiOwoKZnVuY3Rpb24gc2NvcmUodmFsdWU/OiBudW1iZXIgfCBudWxsKSB7CiAgcmV0dXJuIHZhbHVlICE9IG51bGwgPyBgJHt2YWx1ZS50b0ZpeGVkKDApfS8xMDBgIDogIk4vQSI7Cn0KCmZ1bmN0aW9uIGxhYmVsKHZhbHVlPzogc3RyaW5nIHwgbnVsbCkgewogIHJldHVybiB2YWx1ZSA/IHZhbHVlLnJlcGxhY2VBbGwoIl8iLCAiICIpIDogIk4vQSI7Cn0KCmNvbnN0IGhpZGRlbkRpbWVuc2lvbktleXMgPSBuZXcgU2V0KFsKICAicmVwcmVzZW50YXRpb24iLAogICJ0ZW1wbGF0ZSIsCiAgInNvdXJjZV9iYXNpcyIsCiAgInNvdXJjZV9yZWZlcmVuY2VzIiwKICAiYWxpZ25tZW50X3N0YXR1cyIsCl0pOwoKZnVuY3Rpb24gZGltZW5zaW9uTGFiZWwoa2V5OiBzdHJpbmcpIHsKICByZXR1cm4ga2V5CiAgICAucmVwbGFjZSgvX20zcyQvLCAiIChtMy9zKSIpCiAgICAucmVwbGFjZSgvX21jbSQvLCAiIChNQ00pIikKICAgIC5yZXBsYWNlKC9fdG1jJC8sICIgKFRNQykiKQogICAgLnJlcGxhY2UoL19tJC8sICIgKG0pIikKICAgIC5yZXBsYWNlQWxsKCJfIiwgIiAiKTsKfQoKZnVuY3Rpb24gZGltZW5zaW9uVmFsdWUodmFsdWU6IHVua25vd24pIHsKICBpZiAodHlwZW9mIHZhbHVlID09PSAibnVtYmVyIikgewogICAgcmV0dXJuIE51bWJlci5pc0ludGVnZXIodmFsdWUpCiAgICAgID8gdmFsdWUudG9Mb2NhbGVTdHJpbmcoKQogICAgICA6IHZhbHVlLnRvTG9jYWxlU3RyaW5nKHVuZGVmaW5lZCwgeyBtYXhpbXVtRnJhY3Rpb25EaWdpdHM6IDMgfSk7CiAgfQogIHJldHVybiBTdHJpbmcodmFsdWUpLnJlcGxhY2VBbGwoIl8iLCAiICIpOwp9CgpleHBvcnQgZnVuY3Rpb24gVHdpblBhbmVscyh7IHR3aW4gfTogeyB0d2luOiBUd2luUmVzcG9uc2UgfSkgewogIGNvbnN0IGRpbWVuc2lvbnMgPSBPYmplY3QuZW50cmllcyh0d2luLnR3aW4uZGltZW5zaW9ucykuZmlsdGVyKAogICAgKFtrZXksIHZhbHVlXSkgPT4KICAgICAgIWhpZGRlbkRpbWVuc2lvbktleXMuaGFzKGtleSkgJiYgdmFsdWUgIT09IG51bGwgJiYgdmFsdWUgIT09IHVuZGVmaW5lZCwKICApOwoKICByZXR1cm4gKAogICAgPGRpdiBjbGFzc05hbWU9ImNsZWFuLXR3aW4tcGFuZWxzIj4KICAgICAgPHNlY3Rpb24gY2xhc3NOYW1lPSJjbGVhbi1zY29yZS1ncmlkIj4KICAgICAgICA8ZGl2PjxzcGFuPlNJTVJBUyBoZWFsdGg8L3NwYW4+PHN0cm9uZz57c2NvcmUodHdpbi5haS5oZWFsdGhfc2NvcmUpfTwvc3Ryb25nPjxzbWFsbD5SZXNlYXJjaCBwcmVkaWN0aW9uPC9zbWFsbD48L2Rpdj4KICAgICAgICA8ZGl2PjxzcGFuPlNJTVJBUyByaXNrPC9zcGFuPjxzdHJvbmcgc3R5bGU9e3sgY29sb3I6IHJpc2tDb2xvcih0d2luLmFpLnJpc2tfbGV2ZWwpIH19PntzY29yZSh0d2luLmFpLnJpc2tfc2NvcmUpfTwvc3Ryb25nPjxzbWFsbD57bGFiZWwodHdpbi5haS5yaXNrX2xldmVsKX08L3NtYWxsPjwvZGl2PgogICAgICAgIDxkaXY+PHNwYW4+U0lNUkFTIGhhemFyZDwvc3Bhbj48c3Ryb25nIHN0eWxlPXt7IGNvbG9yOiByaXNrQ29sb3IodHdpbi5haS5oYXphcmRfbGV2ZWwpIH19PntzY29yZSh0d2luLmFpLmhhemFyZF9zY29yZSl9PC9zdHJvbmc+PHNtYWxsPntsYWJlbCh0d2luLmFpLmhhemFyZF9sZXZlbCl9PC9zbWFsbD48L2Rpdj4KICAgICAgICA8ZGl2PjxzcGFuPlByZWRpY3Rpb24gY29uZmlkZW5jZTwvc3Bhbj48c3Ryb25nPnt0d2luLmFpLmNvbmZpZGVuY2UgIT0gbnVsbCA/IGAke01hdGgucm91bmQodHdpbi5haS5jb25maWRlbmNlICogMTAwKX0lYCA6ICJOL0EifTwvc3Ryb25nPjxzbWFsbD5Ob3QgYW4gb2ZmaWNpYWwgcmF0aW5nPC9zbWFsbD48L2Rpdj4KICAgICAgPC9zZWN0aW9uPgoKICAgICAgPHNlY3Rpb24gY2xhc3NOYW1lPSJjbGVhbi1wYW5lbCI+CiAgICAgICAgPGhlYWRlciBjbGFzc05hbWU9ImNsZWFuLXBhbmVsLWhlYWRlciI+PGRpdj48c3BhbiBjbGFzc05hbWU9ImNsZWFuLWtpY2tlciI+RVhQRVJJTUVOVEFMPC9zcGFuPjxoMz5SZW1haW5pbmcgdXNlZnVsIGxpZmUgcHJveHk8L2gzPjwvZGl2PjwvaGVhZGVyPgogICAgICAgIDx0YWJsZSBjbGFzc05hbWU9ImNsZWFuLWRhdGEtdGFibGUiPjx0Ym9keT4KICAgICAgICAgIDx0cj48dGg+RXN0aW1hdGVkIHJlbWFpbmluZyBsaWZlPC90aD48dGQ+e3R3aW4uYWkucmVtYWluaW5nX2xpZmVfeWVhcnMgIT0gbnVsbCA/IGAke3R3aW4uYWkucmVtYWluaW5nX2xpZmVfeWVhcnMudG9GaXhlZCgxKX0geWVhcnNgIDogIk4vQSJ9PC90ZD48L3RyPgogICAgICAgICAgPHRyPjx0aD5Fc3RpbWF0ZWQgcmFuZ2U8L3RoPjx0ZD57dHdpbi5haS5ydWxfbG93ZXJfYm91bmQgIT0gbnVsbCAmJiB0d2luLmFpLnJ1bF91cHBlcl9ib3VuZCAhPSBudWxsID8gYCR7dHdpbi5haS5ydWxfbG93ZXJfYm91bmQudG9GaXhlZCgxKX0gLSAke3R3aW4uYWkucnVsX3VwcGVyX2JvdW5kLnRvRml4ZWQoMSl9IHllYXJzYCA6ICJOL0EifTwvdGQ+PC90cj4KICAgICAgICAgIDx0cj48dGg+QmFzaXM8L3RoPjx0ZD57dHdpbi5haS5ydWxfYmFzaXNfdXJsID8gPGEgaHJlZj17dHdpbi5haS5ydWxfYmFzaXNfdXJsfSB0YXJnZXQ9Il9ibGFuayIgcmVsPSJub3JlZmVycmVyIj57dHdpbi5haS5ydWxfYmFzaXMgPz8gIk9wZW4gYmFzaXMgc291cmNlIn08L2E+IDogKHR3aW4uYWkucnVsX2Jhc2lzID8/ICJOL0EiKX08L3RkPjwvdHI+CiAgICAgICAgICA8dHI+PHRoPlN0YXR1czwvdGg+PHRkPntsYWJlbCh0d2luLmFpLnJ1bF9zdGF0dXMpfTwvdGQ+PC90cj4KICAgICAgICAgIDx0cj48dGg+UlVMIGNvbmZpZGVuY2U8L3RoPjx0ZD57dHdpbi5haS5ydWxfY29uZmlkZW5jZSAhPSBudWxsID8gYCR7TWF0aC5yb3VuZCh0d2luLmFpLnJ1bF9jb25maWRlbmNlICogMTAwKX0lYCA6ICJOL0EifTwvdGQ+PC90cj4KICAgICAgICA8L3Rib2R5PjwvdGFibGU+CiAgICAgICAgPHAgY2xhc3NOYW1lPSJjbGVhbi1ub3RlIj5FeHBlcmltZW50YWwgcGxhbm5pbmctbGlmZSBwcm94eSBvbmx5OyBub3QgYW4gb2ZmaWNpYWwgc3RydWN0dXJhbCByZW1haW5pbmctbGlmZSBvciBkYW0tc2FmZXR5IHJhdGluZy48L3A+CiAgICAgIDwvc2VjdGlvbj4KCiAgICAgIDxzZWN0aW9uIGNsYXNzTmFtZT0iY2xlYW4tcGFuZWwiPgogICAgICAgIDxoZWFkZXIgY2xhc3NOYW1lPSJjbGVhbi1wYW5lbC1oZWFkZXIiPjxkaXY+PHNwYW4gY2xhc3NOYW1lPSJjbGVhbi1raWNrZXIiPlNPVVJDRSBCQUNLRUQ8L3NwYW4+PGgzPkRpbWVuc2lvbnMgJiBjaGFyYWN0ZXJpc3RpY3M8L2gzPjwvZGl2PjwvaGVhZGVyPgogICAgICAgIDx0YWJsZSBjbGFzc05hbWU9ImNsZWFuLWRhdGEtdGFibGUiPjx0aGVhZD48dHI+PHRoPlBhcmFtZXRlcjwvdGg+PHRoPlZhbHVlPC90aD48L3RyPjwvdGhlYWQ+PHRib2R5PgogICAgICAgICAge2RpbWVuc2lvbnMubWFwKChba2V5LCB2YWx1ZV0pID0+IDx0ciBrZXk9e2tleX0+PHRkPntkaW1lbnNpb25MYWJlbChrZXkpfTwvdGQ+PHRkPntkaW1lbnNpb25WYWx1ZSh2YWx1ZSl9PC90ZD48L3RyPil9CiAgICAgICAgPC90Ym9keT48L3RhYmxlPgogICAgICAgIDxwIGNsYXNzTmFtZT0iY2xlYW4tbm90ZSI+RGltZW5zaW9ucyBmb2xsb3cgbGlua2VkIHJlY29yZHMuIFVucHJvdmlkZWQgZ2VvbWV0cnkgcmVtYWlucyBwYXJhbWV0cmljL2FwcHJveGltYXRlIHVubGVzcyBtZWFzdXJlZCBnZW9tZXRyeSBpcyBsaW5rZWQuPC9wPgogICAgICA8L3NlY3Rpb24+CgogICAgICA8c2VjdGlvbiBjbGFzc05hbWU9ImNsZWFuLXR3by1jb2x1bW4iPgogICAgICAgIDxhcnRpY2xlIGNsYXNzTmFtZT0iY2xlYW4tcGFuZWwiPjxoMz5SZWNvbW1lbmRhdGlvbnM8L2gzPjx1bCBjbGFzc05hbWU9ImNsZWFuLWxpc3QiPnsodHdpbi5haS5yZWNvbW1lbmRhdGlvbnMgPz8gW10pLm1hcCgoaXRlbSkgPT4gPGxpIGtleT17aXRlbX0+e2l0ZW19PC9saT4pfTwvdWw+PC9hcnRpY2xlPgogICAgICAgIDxhcnRpY2xlIGNsYXNzTmFtZT0iY2xlYW4tcGFuZWwiPjxoMz5XaHkgdGhpcyBwcmVkaWN0aW9uPzwvaDM+PHVsIGNsYXNzTmFtZT0iY2xlYW4tbGlzdCI+e3R3aW4uYWkuZmFjdG9ycy5tYXAoKGl0ZW0pID0+IDxsaSBrZXk9e2l0ZW19PntpdGVtfTwvbGk+KX08L3VsPjwvYXJ0aWNsZT4KICAgICAgPC9zZWN0aW9uPgogICAgPC9kaXY+CiAgKTsKfQo=")
)

[IO.File]::WriteAllBytes(
  ".\frontend\src\features\digital-twin\EvidenceStatePanel.tsx",
  [Convert]::FromBase64String("aW1wb3J0IHR5cGUgeyBFdmlkZW5jZVN0YXRlUmVzcG9uc2UgfSBmcm9tICIuLi8uLi90eXBlcy9ldmlkZW5jZSI7CgpmdW5jdGlvbiBsYWJlbCh2YWx1ZTogc3RyaW5nIHwgbnVsbCB8IHVuZGVmaW5lZCkgewogIHJldHVybiB2YWx1ZSA/IHZhbHVlLnJlcGxhY2VBbGwoIl8iLCAiICIpIDogIk4vQSI7Cn0KCmZ1bmN0aW9uIGRpc3BsYXlWYWx1ZSgKICB2YWx1ZTogbnVtYmVyIHwgc3RyaW5nIHwgbnVsbCB8IHVuZGVmaW5lZCwKICB1bml0Pzogc3RyaW5nIHwgbnVsbCwKKSB7CiAgaWYgKHZhbHVlID09PSBudWxsIHx8IHZhbHVlID09PSB1bmRlZmluZWQpIHJldHVybiAiTi9BIjsKCiAgY29uc3QgcmVuZGVyZWQgPQogICAgdHlwZW9mIHZhbHVlID09PSAibnVtYmVyIgogICAgICA/IE51bWJlci5pc0ludGVnZXIodmFsdWUpCiAgICAgICAgPyB2YWx1ZS50b0xvY2FsZVN0cmluZygpCiAgICAgICAgOiB2YWx1ZS50b0xvY2FsZVN0cmluZyh1bmRlZmluZWQsIHsgbWF4aW11bUZyYWN0aW9uRGlnaXRzOiAzIH0pCiAgICAgIDogU3RyaW5nKHZhbHVlKS5yZXBsYWNlQWxsKCJfIiwgIiAiKTsKCiAgcmV0dXJuIHVuaXQgPyBgJHtyZW5kZXJlZH0gJHt1bml0fWAgOiByZW5kZXJlZDsKfQoKZXhwb3J0IGZ1bmN0aW9uIEV2aWRlbmNlU3RhdGVQYW5lbCh7CiAgc3RhdGUsCn06IHsKICBzdGF0ZTogRXZpZGVuY2VTdGF0ZVJlc3BvbnNlOwp9KSB7CiAgY29uc3QgZW52aXJvbm1lbnQgPSBPYmplY3QuZW50cmllcyhzdGF0ZS5lbnZpcm9ubWVudCk7CgogIGNvbnN0IG9mZmljaWFsQ29uZGl0aW9uID0KICAgIHN0YXRlLmNvbmRpdGlvbi5jb25kaXRpb24gPT09ICJVTktOT1dOIgogICAgICA/ICJOb3QgcHVibGlzaGVkIGluIGxpbmtlZCBvZmZpY2lhbCByZWNvcmRzIgogICAgICA6IGxhYmVsKHN0YXRlLmNvbmRpdGlvbi5jb25kaXRpb24pOwoKICBjb25zdCBvZmZpY2lhbFJpc2sgPQogICAgc3RhdGUuY29uZGl0aW9uLnJpc2sgPT09ICJVTktOT1dOIgogICAgICA/ICJOb3QgcHVibGlzaGVkIGluIGxpbmtlZCBvZmZpY2lhbCByZWNvcmRzIgogICAgICA6IGxhYmVsKHN0YXRlLmNvbmRpdGlvbi5yaXNrKTsKCiAgcmV0dXJuICgKICAgIDxkaXYgY2xhc3NOYW1lPSJjbGVhbi1ldmlkZW5jZS1wYW5lbHMiPgogICAgICA8c2VjdGlvbiBjbGFzc05hbWU9ImNsZWFuLXBhbmVsIj4KICAgICAgICA8aGVhZGVyIGNsYXNzTmFtZT0iY2xlYW4tcGFuZWwtaGVhZGVyIj4KICAgICAgICAgIDxkaXY+CiAgICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT0iY2xlYW4ta2lja2VyIj5HT1ZFUk5NRU5UIEVWSURFTkNFPC9zcGFuPgogICAgICAgICAgICA8aDM+T2ZmaWNpYWwgc2FmZXR5ICYgc3RydWN0dXJhbCBldmlkZW5jZTwvaDM+CiAgICAgICAgICA8L2Rpdj4KICAgICAgICA8L2hlYWRlcj4KCiAgICAgICAgPHRhYmxlIGNsYXNzTmFtZT0iY2xlYW4tZGF0YS10YWJsZSI+CiAgICAgICAgICA8dGJvZHk+CiAgICAgICAgICAgIDx0cj48dGg+T2ZmaWNpYWwgc3RydWN0dXJhbCBjb25kaXRpb248L3RoPjx0ZD57b2ZmaWNpYWxDb25kaXRpb259PC90ZD48L3RyPgogICAgICAgICAgICA8dHI+PHRoPk9mZmljaWFsIHN0cnVjdHVyYWwgcmlzazwvdGg+PHRkPntvZmZpY2lhbFJpc2t9PC90ZD48L3RyPgogICAgICAgICAgICA8dHI+PHRoPkV2aWRlbmNlIHN0cmVuZ3RoPC90aD48dGQ+e2xhYmVsKHN0YXRlLmV2aWRlbmNlX3N0cmVuZ3RoKX08L3RkPjwvdHI+CiAgICAgICAgICAgIDx0cj48dGg+QXNzZXQgaWRlbnRpdHk8L3RoPjx0ZD57bGFiZWwoc3RhdGUuYXNzZXQuaWRlbnRpdHlfc3RhdHVzKX08L3RkPjwvdHI+CiAgICAgICAgICAgIDx0cj48dGg+RGlzdHJpY3Q8L3RoPjx0ZD57c3RhdGUuYXNzZXQuZGlzdHJpY3QgPz8gIk4vQSJ9PC90ZD48L3RyPgogICAgICAgICAgICA8dHI+PHRoPk93bmVyPC90aD48dGQ+e3N0YXRlLmFzc2V0Lm93bmVyID8/ICJOL0EifTwvdGQ+PC90cj4KICAgICAgICAgIDwvdGJvZHk+CiAgICAgICAgPC90YWJsZT4KCiAgICAgICAgPHAgY2xhc3NOYW1lPSJjbGVhbi1ub3RlIj4KICAgICAgICAgIE1pc3Npbmcgb2ZmaWNpYWwgY29uZGl0aW9uL3Jpc2sgdmFsdWVzIGFyZSBub3QgcmVwbGFjZWQgd2l0aCBTSU1SQVMgcHJlZGljdGlvbnMuCiAgICAgICAgPC9wPgogICAgICA8L3NlY3Rpb24+CgogICAgICA8c2VjdGlvbiBjbGFzc05hbWU9ImNsZWFuLXBhbmVsIj4KICAgICAgICA8aGVhZGVyIGNsYXNzTmFtZT0iY2xlYW4tcGFuZWwtaGVhZGVyIj4KICAgICAgICAgIDxkaXY+CiAgICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT0iY2xlYW4ta2lja2VyIj5MSU5LRUQgUkVDT1JEUzwvc3Bhbj4KICAgICAgICAgICAgPGgzPlJlYWwgb2ZmaWNpYWwgZXZpZGVuY2U8L2gzPgogICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9oZWFkZXI+CgogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJjbGVhbi10YWJsZS1zY3JvbGwiPgogICAgICAgICAgPHRhYmxlIGNsYXNzTmFtZT0iY2xlYW4tZGF0YS10YWJsZSBldmlkZW5jZS1yZWNvcmQtdGFibGUiPgogICAgICAgICAgICA8dGhlYWQ+CiAgICAgICAgICAgICAgPHRyPgogICAgICAgICAgICAgICAgPHRoPkZpZWxkPC90aD4KICAgICAgICAgICAgICAgIDx0aD5WYWx1ZTwvdGg+CiAgICAgICAgICAgICAgICA8dGg+QXV0aG9yaXR5PC90aD4KICAgICAgICAgICAgICAgIDx0aD5BZ2VuY3kgLyBzb3VyY2U8L3RoPgogICAgICAgICAgICAgICAgPHRoPkRvY3VtZW50PC90aD4KICAgICAgICAgICAgICAgIDx0aD5Db25maWRlbmNlPC90aD4KICAgICAgICAgICAgICA8L3RyPgogICAgICAgICAgICA8L3RoZWFkPgoKICAgICAgICAgICAgPHRib2R5PgogICAgICAgICAgICAgIHtzdGF0ZS5ldmlkZW5jZS5tYXAoKGl0ZW0pID0+ICgKICAgICAgICAgICAgICAgIDx0ciBrZXk9e2l0ZW0uaWR9PgogICAgICAgICAgICAgICAgICA8dGQ+e2xhYmVsKGl0ZW0uZmllbGRfbmFtZSl9PC90ZD4KICAgICAgICAgICAgICAgICAgPHRkPgogICAgICAgICAgICAgICAgICAgIHtpdGVtLnRleHRfdmFsdWUgPz8KICAgICAgICAgICAgICAgICAgICAgIGRpc3BsYXlWYWx1ZShpdGVtLm51bWVyaWNfdmFsdWUsIGl0ZW0udW5pdCl9CiAgICAgICAgICAgICAgICAgIDwvdGQ+CiAgICAgICAgICAgICAgICAgIDx0ZD57bGFiZWwoaXRlbS5hdXRob3JpdHlfbGV2ZWwpfTwvdGQ+CiAgICAgICAgICAgICAgICAgIDx0ZD57aXRlbS5hZ2VuY3kgPz8gaXRlbS5zb3VyY2VfbmFtZSA/PyAiTi9BIn08L3RkPgogICAgICAgICAgICAgICAgICA8dGQ+CiAgICAgICAgICAgICAgICAgICAge2l0ZW0uZG9jdW1lbnRfdXJsID8gKAogICAgICAgICAgICAgICAgICAgICAgPGEKICAgICAgICAgICAgICAgICAgICAgICAgaHJlZj17aXRlbS5kb2N1bWVudF91cmx9CiAgICAgICAgICAgICAgICAgICAgICAgIHRhcmdldD0iX2JsYW5rIgogICAgICAgICAgICAgICAgICAgICAgICByZWw9Im5vcmVmZXJyZXIiCiAgICAgICAgICAgICAgICAgICAgICA+CiAgICAgICAgICAgICAgICAgICAgICAgIHtpdGVtLmRvY3VtZW50X3RpdGxlID8/ICJPZmZpY2lhbCBkb2N1bWVudCJ9CiAgICAgICAgICAgICAgICAgICAgICA8L2E+CiAgICAgICAgICAgICAgICAgICAgKSA6ICgKICAgICAgICAgICAgICAgICAgICAgIGl0ZW0uZG9jdW1lbnRfdGl0bGUgPz8gIk4vQSIKICAgICAgICAgICAgICAgICAgICApfQogICAgICAgICAgICAgICAgICA8L3RkPgogICAgICAgICAgICAgICAgICA8dGQ+CiAgICAgICAgICAgICAgICAgICAge2l0ZW0uY29uZmlkZW5jZV9zY29yZSAhPSBudWxsCiAgICAgICAgICAgICAgICAgICAgICA/IGAke01hdGgucm91bmQoaXRlbS5jb25maWRlbmNlX3Njb3JlICogMTAwKX0lYAogICAgICAgICAgICAgICAgICAgICAgOiAiTi9BIn0KICAgICAgICAgICAgICAgICAgPC90ZD4KICAgICAgICAgICAgICAgIDwvdHI+CiAgICAgICAgICAgICAgKSl9CgogICAgICAgICAgICAgIHtzdGF0ZS5ldmlkZW5jZS5sZW5ndGggPT09IDAgJiYgKAogICAgICAgICAgICAgICAgPHRyPgogICAgICAgICAgICAgICAgICA8dGQgY29sU3Bhbj17Nn0+Tm8gbGlua2VkIG9mZmljaWFsIGV2aWRlbmNlIHJlY29yZC48L3RkPgogICAgICAgICAgICAgICAgPC90cj4KICAgICAgICAgICAgICApfQogICAgICAgICAgICA8L3Rib2R5PgogICAgICAgICAgPC90YWJsZT4KICAgICAgICA8L2Rpdj4KCiAgICAgICAgPHAgY2xhc3NOYW1lPSJjbGVhbi1ub3RlIj4KICAgICAgICAgIEdvdmVybmFuY2Uvc2FmZXR5IHJlY29yZHMgc3VjaCBhcyBhbiBFbWVyZ2VuY3kgQWN0aW9uIFBsYW4gYXJlIHJlYWwKICAgICAgICAgIG9mZmljaWFsIGV2aWRlbmNlLCBidXQgZG8gbm90IGJ5IHRoZW1zZWx2ZXMgZXN0YWJsaXNoIGEgc3RydWN0dXJhbC1jb25kaXRpb24gcmF0aW5nLgogICAgICAgIDwvcD4KICAgICAgPC9zZWN0aW9uPgoKICAgICAgPHNlY3Rpb24gY2xhc3NOYW1lPSJjbGVhbi1wYW5lbCI+CiAgICAgICAgPGhlYWRlciBjbGFzc05hbWU9ImNsZWFuLXBhbmVsLWhlYWRlciI+CiAgICAgICAgICA8ZGl2PgogICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9ImNsZWFuLWtpY2tlciI+T0JTRVJWRUQgREFUQTwvc3Bhbj4KICAgICAgICAgICAgPGgzPkdvdmVybm1lbnQgZW52aXJvbm1lbnRhbCBvYnNlcnZhdGlvbnM8L2gzPgogICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9oZWFkZXI+CgogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJjbGVhbi10YWJsZS1zY3JvbGwiPgogICAgICAgICAgPHRhYmxlIGNsYXNzTmFtZT0iY2xlYW4tZGF0YS10YWJsZSI+CiAgICAgICAgICAgIDx0aGVhZD4KICAgICAgICAgICAgICA8dHI+CiAgICAgICAgICAgICAgICA8dGg+VmFyaWFibGU8L3RoPgogICAgICAgICAgICAgICAgPHRoPlZhbHVlPC90aD4KICAgICAgICAgICAgICAgIDx0aD5Tb3VyY2U8L3RoPgogICAgICAgICAgICAgICAgPHRoPk9ic2VydmVkIGF0PC90aD4KICAgICAgICAgICAgICAgIDx0aD5RdWFsaXR5PC90aD4KICAgICAgICAgICAgICAgIDx0aD5Db25maWRlbmNlPC90aD4KICAgICAgICAgICAgICA8L3RyPgogICAgICAgICAgICA8L3RoZWFkPgoKICAgICAgICAgICAgPHRib2R5PgogICAgICAgICAgICAgIHtlbnZpcm9ubWVudC5tYXAoKFtrZXksIGl0ZW1dKSA9PiAoCiAgICAgICAgICAgICAgICA8dHIga2V5PXtrZXl9PgogICAgICAgICAgICAgICAgICA8dGQ+e2xhYmVsKGtleSl9PC90ZD4KICAgICAgICAgICAgICAgICAgPHRkPntkaXNwbGF5VmFsdWUoaXRlbS52YWx1ZSwgaXRlbS51bml0KX08L3RkPgogICAgICAgICAgICAgICAgICA8dGQ+e2l0ZW0uc291cmNlID8/ICJOL0EifTwvdGQ+CiAgICAgICAgICAgICAgICAgIDx0ZD4KICAgICAgICAgICAgICAgICAgICB7aXRlbS5vYnNlcnZlZF9hdAogICAgICAgICAgICAgICAgICAgICAgPyBuZXcgRGF0ZShpdGVtLm9ic2VydmVkX2F0KS50b0xvY2FsZVN0cmluZygpCiAgICAgICAgICAgICAgICAgICAgICA6ICJOL0EifQogICAgICAgICAgICAgICAgICA8L3RkPgogICAgICAgICAgICAgICAgICA8dGQ+e2xhYmVsKGl0ZW0ucXVhbGl0eV9mbGFnKX08L3RkPgogICAgICAgICAgICAgICAgICA8dGQ+CiAgICAgICAgICAgICAgICAgICAge2l0ZW0uY29uZmlkZW5jZSAhPSBudWxsCiAgICAgICAgICAgICAgICAgICAgICA/IGAke01hdGgucm91bmQoaXRlbS5jb25maWRlbmNlICogMTAwKX0lYAogICAgICAgICAgICAgICAgICAgICAgOiAiTi9BIn0KICAgICAgICAgICAgICAgICAgPC90ZD4KICAgICAgICAgICAgICAgIDwvdHI+CiAgICAgICAgICAgICAgKSl9CgogICAgICAgICAgICAgIHtlbnZpcm9ubWVudC5sZW5ndGggPT09IDAgJiYgKAogICAgICAgICAgICAgICAgPHRyPgogICAgICAgICAgICAgICAgICA8dGQgY29sU3Bhbj17Nn0+CiAgICAgICAgICAgICAgICAgICAgTm8gbWF0Y2hlZCBnb3Zlcm5tZW50IGVudmlyb25tZW50YWwgb2JzZXJ2YXRpb24uCiAgICAgICAgICAgICAgICAgIDwvdGQ+CiAgICAgICAgICAgICAgICA8L3RyPgogICAgICAgICAgICAgICl9CiAgICAgICAgICAgIDwvdGJvZHk+CiAgICAgICAgICA8L3RhYmxlPgogICAgICAgIDwvZGl2PgogICAgICA8L3NlY3Rpb24+CiAgICA8L2Rpdj4KICApOwp9Cg==")
)

Write-Host "TwinPanels.tsx restored" -ForegroundColor Green
Write-Host "EvidenceStatePanel.tsx restored" -ForegroundColor Green

Write-Host "`n=== 2. TARGETED GLOBAL CORRUPTION REPAIR ===" -ForegroundColor Cyan

@'
from pathlib import Path
import re

src = Path("frontend/src")
changed = []

# Only expressions we have actually observed being corrupted during this merge.
replacements = [
    (r'Number\(([^()\n]+?)\s\?\s0\)', r'Number(\1 ?? 0)'),
    (r'String\(([^()\n]+?)\s\?\s""\)', r'String(\1 ?? "")'),
    (r'\b(record\.[A-Za-z_]\w*)\s\?\s(record\.[A-Za-z_]\w*)', r'\1 ?? \2'),
    (r'\b(inspection\.[A-Za-z_]\w*)\s\?\s(inspection\.[A-Za-z_]\w*)', r'\1 ?? \2'),
    (r'\b(asset\.[A-Za-z_]\w*)\s\?\s(asset\.[A-Za-z_]\w*)', r'\1 ?? \2'),
    (r'\b(item\.[A-Za-z_]\w*)\s\?\s(item\.[A-Za-z_]\w*)', r'\1 ?? \2'),
]

for p in src.rglob("*"):
    if not p.is_file() or p.suffix not in {".ts", ".tsx"}:
        continue

    text = p.read_text(encoding="utf-8-sig")
    original = text

    for pattern, replacement in replacements:
        text = re.sub(pattern, replacement, text)

    if text != original:
        p.write_text(text, encoding="utf-8")
        changed.append(str(p))

print("Targeted files repaired:", len(changed))
for item in changed:
    print(" ", item)
'@ | py -

Write-Host "`n=== 3. FULL TYPESCRIPT/VITE BUILD ===" -ForegroundColor Cyan

Push-Location ".\frontend"

if (Test-Path ".\node_modules\.vite") {
  Remove-Item ".\node_modules\.vite" -Recurse -Force -ErrorAction SilentlyContinue
}

npm run build
$buildExit = $LASTEXITCODE

Pop-Location

if ($buildExit -ne 0) {
  Write-Host "`nBUILD STILL HAS A DIFFERENT SOURCE ERROR." -ForegroundColor Red
  Write-Host "Running container was NOT replaced." -ForegroundColor Yellow
  Write-Host "Backup: $backup"
  throw "SEND ONLY THE FIRST NEW FILE:LINE ERROR"
}

Write-Host "`nFRONTEND BUILD PASS" -ForegroundColor Green

Write-Host "`n=== 4. BACKEND HEALTH ===" -ForegroundColor Cyan

py -m py_compile ".\backend\app\main.py"
if ($LASTEXITCODE -ne 0) {
  throw "BACKEND COMPILE FAILED"
}

docker compose ps

Write-Host "`n=== 5. REBUILD FRESH FRONTEND CONTAINER ===" -ForegroundColor Cyan

docker compose build frontend
if ($LASTEXITCODE -ne 0) {
  throw "FRONTEND DOCKER IMAGE BUILD FAILED"
}

docker compose stop frontend
docker compose rm -f frontend
docker compose up -d --force-recreate --renew-anon-volumes frontend

Start-Sleep -Seconds 7

Write-Host "`n=== 6. VERIFY EXACT SOURCE INSIDE CONTAINER ===" -ForegroundColor Cyan

docker compose exec -T frontend sh -lc "sed -n '25,45p' /app/src/features/digital-twin/TwinPanels.tsx"
docker compose exec -T frontend sh -lc "sed -n '35,60p' /app/src/features/digital-twin/EvidenceStatePanel.tsx"

Write-Host "`n=== 7. LIVE CONNECTION CHECK ===" -ForegroundColor Cyan

function Test-Url {
  param([string]$Name,[string]$Url)
  $code = curl.exe -s -o NUL -w "%{http_code}" $Url
  if ($code -eq "200") {
    Write-Host ("{0,-22} PASS ({1})" -f $Name,$code) -ForegroundColor Green
  } else {
    Write-Host ("{0,-22} CHECK ({1})" -f $Name,$code) -ForegroundColor Yellow
  }
}

Test-Url "Frontend" "http://localhost:5173/"
Test-Url "Digital Twin" "http://localhost:5173/digital-twin"
Test-Url "Backend docs" "http://localhost:8000/docs"
Test-Url "Assets API" "http://localhost:8000/api/v1/assets?limit=3"
Test-Url "Twin API" "http://localhost:8000/api/v1/assets/AP_DAM_00001/twin"
Test-Url "Model status" "http://localhost:8000/api/v1/analytics/models/status"

Write-Host "`n============================================================" -ForegroundColor Green
Write-Host "TWIN SOURCE RESET + BUILD COMPLETE" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Green
Write-Host "Backup: $backup"

Start-Process "http://localhost:5173/digital-twin"
